[package]
name = "M1P1-lean"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "edfa2061547510a41db4d0d471130badcb92ef20"}
