[package]
name = "M1P1-lean"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "50a03f76bb89ee5cf9d9703f78e1eb2139d9b609"}
